@startuml

title __LOGIN's Class Diagram__\n

  namespace login {
    class login.Login {
        + profile_pic : Circle
        + root : AnchorPane
        - btnClose : Button
        - btnLogin : Button
        - btnMinimize : Button
        - lbImage : Label
        + initialize()
        + login_as_google()
        - onMinimize()
        - onclose()
    }
  }
  

  namespace login {
    abstract class login.OAuthAuthenticator {
        - accessCode : String
        - accessToken : String
        - accessedJsonData : JSONObject
        - attemptRecieved : boolean
        - clientID : String
        - clientSecret : String
        - gotData : boolean
        - isLogin : boolean
        - loginAttempted : boolean
        - redirectUri : String
        - stage : Stage
        - xOffset : double
        - yOffset : double
        + OAuthAuthenticator()
        + getAccessCode()
        + getAccessToken()
        + getClientID()
        + getClientSecret()
        + getJsonData()
        + getRedirectUri()
        + hasFinishedSuccessfully()
        + startLogin()
        {abstract} ~ getApiAccessParams()
        {abstract} ~ getApiAccessUrl()
        {abstract} ~ getApiTokenUrl()
        {abstract} ~ getWebUrl()
        - closeStage()
        - doGetAccessTokenRequest()
        - doGetAccountInfo()
        - notifyLoginViewCompleted()
    }
  }
  

  namespace login {
    interface login.OAuthCompletedCallback {
        {abstract} + oAuthCallback()
    }
  }
  

  namespace login {
    class login.OAuthGoogleAuthenticator {
        - GOOGLE_apiScope : String
        + OAuthGoogleAuthenticator()
        ~ getApiAccessParams()
        ~ getApiAccessUrl()
        ~ getApiTokenUrl()
        ~ getWebUrl()
    }
  }
  

  namespace login {
    enum OAuthType {
      GOOGLE
    }
  }
  

  login.Login .up.|> javafx.fxml.Initializable
  login.OAuthGoogleAuthenticator -up-|> login.OAuthAuthenticator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
