@startuml

title __DTO's Class Diagram__\n

  namespace DTO {
    class DTO.DoctorDTO {
        - birthdate : String
        - email : String
        - fullName : String
        - gender : String
        - id : UUID
        - ip : String
        - specialist : String
        + DoctorDTO()
        + DoctorDTO()
        + getBirthdate()
        + getEmail()
        + getFullName()
        + getGender()
        + getId()
        + getIp()
        + getSpecialist()
        + setBirthdate()
        + setEmail()
        + setFullName()
        + setGender()
        + setId()
        + setIp()
        + setSpecialist()
    }
  }
  

  namespace DTO {
    class DTO.FullTaskDTO {
        - doctorID : UUID
        - folderName : String
        - id : UUID
        - idPatient : UUID
        - idTechnician : UUID
        - note : String
        + FullTaskDTO()
        + FullTaskDTO()
        + getDoctorID()
        + getFolderName()
        + getId()
        + getIdPatient()
        + getIdTechnician()
        + getNote()
        + setDoctorID()
        + setFolderName()
        + setId()
        + setIdPatient()
        + setIdTechnician()
        + setNote()
    }
  }
  

  namespace DTO {
    class DTO.HistoryDTO {
        - birthDate : String
        - date : String
        - eID : UUID
        - gender : String
        - id : int
        - patientName : String
        - status : String
        + HistoryDTO()
        + HistoryDTO()
        + getBirthDate()
        + getDate()
        + getGender()
        + getId()
        + getPatientName()
        + getStatus()
        + geteID()
        + setBirthDate()
        + setDate()
        + setGender()
        + setId()
        + setPatientName()
        + setStatus()
        + seteID()
    }
  }
  

  namespace DTO {
    class DTO.ImageDTO {
        - confirm_date : String
        - data : byte[]
        - fullPath : String
        - id : int
        - imageId : UUID
        - type : String
        + ImageDTO()
        + ImageDTO()
        + getConfirm_date()
        + getData()
        + getFullPath()
        + getId()
        + getImageId()
        + getType()
        + setConfirm_date()
        + setData()
        + setFullPath()
        + setId()
        + setImageId()
        + setType()
    }
  }
  

  namespace DTO {
    class DTO.PatientDTO {
        - dateOfBirth : String
        - fullname : String
        - gender : String
        - healthInsurance : String
        - id : UUID
        - phone : String
        + PatientDTO()
        + PatientDTO()
        + getDateOfBirth()
        + getFullname()
        + getGender()
        + getHealthInsurance()
        + getId()
        + getPhone()
        + setDateOfBirth()
        + setFullname()
        + setGender()
        + setHealthInsurance()
        + setId()
        + setPhone()
    }
  }
  

  namespace DTO {
    class DTO.TaskDTO {
        - birthDate : String
        - date : String
        - eID : UUID
        - gender : String
        - id : int
        - patientName : String
        - status : String
        + TaskDTO()
        + TaskDTO()
        + getBirthDate()
        + getDate()
        + getGender()
        + getId()
        + getPatientName()
        + getStatus()
        + geteID()
        + setBirthDate()
        + setDate()
        + setGender()
        + setId()
        + setPatientName()
        + setStatus()
        + seteID()
    }
  }
  

  namespace DTO {
    class DTO.TechnicianDTO {
        - birthdate : String
        - email : String
        - fullName : String
        - gender : String
        - id : UUID
        - ip : String
        - specialist : String
        + TechnicianDTO()
        + TechnicianDTO()
        + getBirthdate()
        + getEmail()
        + getFullName()
        + getGender()
        + getId()
        + getIp()
        + getSpecialist()
        + setBirthdate()
        + setEmail()
        + setFullName()
        + setGender()
        + setId()
        + setIp()
        + setSpecialist()
    }
  }
  

  namespace DTO {
    class DTO.tTaskDTO {
        - date : String
        - doctorName : String
        - eID : UUID
        - id : int
        - patientName : String
        - status : String
        + getDate()
        + getDoctorName()
        + getId()
        + getPatientName()
        + getStatus()
        + geteID()
        + setDate()
        + setDoctorName()
        + setId()
        + setPatientName()
        + setStatus()
        + seteID()
        + tTaskDTO()
        + tTaskDTO()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
