@startuml

title __ENTITY's Class Diagram__\n

  namespace Entity {
    class Entity.Doctor {
        - birthdate : String
        - createDate : String
        - email : String
        - fullName : String
        - gender : String
        - id : UUID
        - ip : String
        - specialist : String
        - status : String
        - updateDate : String
        + Doctor()
        + Doctor()
        + getBirthdate()
        + getCreateDate()
        + getEmail()
        + getFullName()
        + getGender()
        + getId()
        + getIp()
        + getSpecialist()
        + getStatus()
        + getUpdateDate()
        + setBirthdate()
        + setCreateDate()
        + setEmail()
        + setFullName()
        + setGender()
        + setId()
        + setIp()
        + setSpecialist()
        + setStatus()
        + setUpdateDate()
        + toString()
    }
  }
  

  namespace Entity {
    class Entity.Image {
        - confirmDate : String
        - id : UUID
        - idDoctor : UUID
        - idPatient : UUID
        - idTask : UUID
        - imageData : byte[]
        - status : String
        - typeOfTumor : String
        + Image()
        + Image()
        + getConfirmDate()
        + getId()
        + getIdDoctor()
        + getIdPatient()
        + getIdTask()
        + getImageData()
        + getStatus()
        + getTypeOfTumor()
        + setConfirmDate()
        + setId()
        + setIdDoctor()
        + setIdPatient()
        + setIdTask()
        + setImageData()
        + setStatus()
        + setTypeOfTumor()
    }
  }
  

  namespace Entity {
    class Entity.Patient {
        - birthdate : String
        - createDate : String
        - fullName : String
        - gender : String
        - healthInsuranceNumber : String
        - id : UUID
        - phone : String
        - status : String
        - updateDate : String
        + Patient()
        + Patient()
        + getBirthdate()
        + getCreateDate()
        + getFullName()
        + getGender()
        + getHealthInsuranceNember()
        + getId()
        + getPhone()
        + getStatus()
        + getUpdateDate()
        + setBirthdate()
        + setCreateDate()
        + setFullName()
        + setGender()
        + setHealthInsuranceNember()
        + setId()
        + setPhone()
        + setStatus()
        + setUpdateDate()
    }
  }
  

  namespace Entity {
    class Entity.Task {
        - folderName : String
        - id : UUID
        - idDoctor : UUID
        - idPatient : UUID
        - idTechnician : UUID
        - note : String
        - predictDate : String
        - predictStatus : String
        - result : String
        - status : String
        - uploadDate : String
        - uploadStatus : String
        + Task()
        + Task()
        + getFolderName()
        + getId()
        + getIdDoctor()
        + getIdPatient()
        + getIdTechnician()
        + getNote()
        + getPredictDate()
        + getPredictStatus()
        + getResult()
        + getStatus()
        + getUploadDate()
        + getUploadStatus()
        + setFolderName()
        + setId()
        + setIdDoctor()
        + setIdPatient()
        + setIdTechnician()
        + setNote()
        + setPredictDate()
        + setPredictStatus()
        + setResult()
        + setStatus()
        + setUploadDate()
        + setUploadStatus()
    }
  }
  

  namespace Entity {
    class Entity.Technician {
        - birthdate : String
        - createDate : String
        - email : String
        - fullName : String
        - gender : String
        - id : UUID
        - ip : String
        - specialist : String
        - status : String
        - updateDate : String
        + Technician()
        + Technician()
        + getBirthdate()
        + getCreateDate()
        + getEmail()
        + getFullName()
        + getGender()
        + getId()
        + getIp()
        + getSpecialist()
        + getStatus()
        + getUpdateDate()
        + setBirthdate()
        + setCreateDate()
        + setEmail()
        + setFullName()
        + setGender()
        + setId()
        + setIp()
        + setSpecialist()
        + setStatus()
        + setUpdateDate()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
